package io.redskap.lambda.runtime.util;

public interface ReservedEnvironmentVariables {
    String HANDLER = "_HANDLER";
    String X_AMZN_TRACE_ID  = "_X_AMZN_TRACE_ID";
    String AWS_REGION = "AWS_REGION";
    String AWS_EXECUTION_ENV = "AWS_EXECUTION_ENV";
    String AWS_LAMBDA_FUNCTION_NAME = "AWS_LAMBDA_FUNCTION_NAME";
    String AWS_LAMBDA_FUNCTION_MEMORY_SIZE = "AWS_LAMBDA_FUNCTION_MEMORY_SIZE";
    String AWS_LAMBDA_FUNCTION_VERSION = "AWS_LAMBDA_FUNCTION_VERSION";
    String AWS_LAMBDA_INITIALIZATION_TYPE  = "AWS_LAMBDA_INITIALIZATION_TYPE";
    String AWS_LAMBDA_LOG_GROUP_NAME = "AWS_LAMBDA_LOG_GROUP_NAME";
    String AWS_LAMBDA_LOG_STREAM_NAME = "AWS_LAMBDA_LOG_STREAM_NAME";
    String AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID";
    String AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY";
    String AWS_SESSION_TOKEN = "AWS_SESSION_TOKEN";
    String AWS_LAMBDA_RUNTIME_API = "AWS_LAMBDA_RUNTIME_API";
    String LAMBDA_TASK_ROOT = "LAMBDA_TASK_ROOT";
    String LAMBDA_RUNTIME_DIR = "LAMBDA_RUNTIME_DIR";
    String TZ = "TZ";
}
